# Generated by Django 3.2.8 on 2021-10-08 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyLoanOne',
            fields=[
                ('national_id_number', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplyLoanTwo',
            fields=[
                ('date_of_birth', models.DateField()),
                ('phone_number', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=250)),
                ('passport', models.FileField(blank=True, null=True, upload_to='media/app_req')),
                ('next_of_kin_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliction.applyloanone')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('next_of_kin_number', models.PositiveIntegerField()),
                ('next_of_kin_email', models.EmailField(max_length=250)),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliction.applyloantwo')),
            ],
        ),
    ]
