# Generated by Django 3.2.9 on 2021-11-19 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appliction', '0002_updateprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id_number', models.PositiveSmallIntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('income_level', models.DecimalField(decimal_places=2, max_digits=6)),
                ('guaranter_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='applyloantwo',
            name='applicant_id',
        ),
        migrations.DeleteModel(
            name='ApplyLoanOne',
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliction.loanapplication'),
        ),
        migrations.DeleteModel(
            name='ApplyLoanTwo',
        ),
    ]
