# Generated by Django 3.2.9 on 2021-11-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliction', '0003_auto_20211119_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextofkin',
            name='income_level',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='id_number',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='income_level',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
