# Generated by Django 3.2.9 on 2021-11-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliction', '0004_auto_20211119_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='repayment_period_in_months',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
