# Generated by Django 3.2.9 on 2021-11-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliction', '0006_alter_loanapplication_repayment_period_in_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
