# Generated by Django 3.2.9 on 2021-11-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliction', '0007_loanapplication_approve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='approve',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_status',
            field=models.CharField(choices=[('new', 'new'), ('approved', 'approved'), ('disbursed', 'disbursed'), ('rejected', 'rejected'), ('closed', 'closed')], default='new', max_length=20),
        ),
    ]
