# Generated by Django 3.2.9 on 2021-11-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliction', '0008_auto_20211119_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='amount_applied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('disbursed', 'disbursed'), ('rejected', 'rejected'), ('closed', 'closed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='phone_number',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
