# Generated by Django 3.2.9 on 2021-11-20 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appliction', '0009_auto_20211119_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(choices=[('debit', 'debit'), ('credit', 'credit')], default='debit', max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='loanapplication',
            old_name='guaranter_id',
            new_name='loan_id',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='guarantor_email',
            field=models.EmailField(default='abc@gmail.com', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='guarantor_id',
            field=models.PositiveSmallIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='guarantor_name',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='gurantor_income_level',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='NextOfKin',
        ),
        migrations.AddField(
            model_name='repayment',
            name='loan_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='appliction.loanapplication'),
        ),
    ]
