# Generated by Django 3.2.9 on 2021-11-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliction', '0010_auto_20211120_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
