# Generated by Django 3.2.9 on 2021-11-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliction', '0011_alter_loanapplication_loan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='select',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
