# Generated by Django 3.2.9 on 2021-11-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliction', '0014_alter_loanapplication_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AddField(
            model_name='updateprofile',
            name='profile_pic',
            field=models.ImageField(default='undraw_profile.svg', upload_to='Profile/'),
        ),
        migrations.AlterField(
            model_name='updateprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='updateprofile',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='updateprofile',
            name='id_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='updateprofile',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
