# Generated by Django 3.2.9 on 2021-11-23 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appliction', '0015_auto_20211121_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repayment',
            name='loan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appliction.loanapplication'),
        ),
    ]
