# Generated by Django 3.2.9 on 2021-11-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliction', '0017_auto_20211123_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='intrest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
